"""
Builds the consolidated daily patient risk report -- the "final deliverable
of the running system" the assignment brief asks for: a report that answers
the business question by joining vitals trends with the latest lab results.

Produces two files per sim_day under data/reports/:
  daily_risk_report_{sim_day}.html  -- human-readable report with a ward
      risk-distribution chart and a per-patient table (reason codes, delta
      vs. yesterday), for screenshotting into the project report.
  daily_risk_report_{sim_day}.csv   -- the same per-patient rows, plain CSV,
      for anyone who wants to load it into a spreadsheet.

Invoked by Airflow's build_report task after run_batch_job succeeds.
"""

from __future__ import annotations

import csv
import io
import os
import sys

import matplotlib

matplotlib.use("Agg")  # headless -- no display available inside a container
import base64  # noqa: E402

import matplotlib.pyplot as plt  # noqa: E402
import psycopg2  # noqa: E402
import psycopg2.extras  # noqa: E402
from jinja2 import Template  # noqa: E402

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from common.logging_setup import configure_logging  # noqa: E402
from config.settings import get_settings  # noqa: E402

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Daily Patient Risk Report -- {{ sim_day }}</title>
<style>
  body { font-family: -apple-system, Segoe UI, Arial, sans-serif; margin: 2rem; color: #1a1a1a; background: #fafafa; }
  h1 { margin-bottom: 0.2rem; }
  .subtitle { color: #666; margin-top: 0; }
  table { border-collapse: collapse; width: 100%; margin-top: 1rem; background: white; }
  th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; font-size: 0.9rem; }
  th { background: #f0f0f0; }
  .band-high { background: #fde2e2; }
  .band-medium { background: #fff4d6; }
  .band-low { background: #e6f6e6; }
  .delta-up { color: #b71c1c; font-weight: bold; }
  .delta-down { color: #1b5e20; font-weight: bold; }
  .reason-codes { font-size: 0.8rem; color: #555; }
  img { max-width: 480px; margin-top: 1rem; }
  .section { margin-bottom: 2rem; }
</style>
</head>
<body>
  <h1>Daily Patient Risk Report</h1>
  <p class="subtitle">Simulated day: {{ sim_day }} &middot; Generated by processing/batch_job.py + serving/report_builder.py</p>

  <div class="section">
    <h2>Ward risk distribution</h2>
    <img src="data:image/png;base64,{{ chart_b64 }}" alt="Ward risk distribution chart">
  </div>

  <div class="section">
    <h2>Per-patient risk (vitals + lab-adjusted)</h2>
    <table>
      <tr>
        <th>Patient</th><th>Ward/Bed</th><th>Vitals score</th><th>Vitals band</th>
        <th>Abnormal labs</th><th>Adjusted score</th><th>Risk band</th>
        <th>vs yesterday</th><th>Reason codes</th>
      </tr>
      {% for r in rows %}
      <tr class="band-{{ r.risk_band }}">
        <td>{{ r.name }} ({{ r.patient_id }})</td>
        <td>{{ r.ward }}/{{ r.bed }}</td>
        <td>{{ r.vitals_score }}</td>
        <td>{{ r.vitals_band }}</td>
        <td>{{ r.abnormal_test_count }}</td>
        <td>{{ r.adjusted_risk_score }}</td>
        <td>{{ r.risk_band }}</td>
        <td>
          {% if r.delta_direction == 'deteriorating' %}<span class="delta-up">&uarr; deteriorating ({{ r.score_delta }})</span>
          {% elif r.delta_direction == 'improving' %}<span class="delta-down">&darr; improving ({{ r.score_delta }})</span>
          {% elif r.delta_direction == 'new' %}first day tracked
          {% else %}stable{% endif %}
        </td>
        <td class="reason-codes">{{ r.reason_codes }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>

  <div class="section">
    <h2>Recent clinical alerts (speed layer, last 24h)</h2>
    <table>
      <tr><th>Patient</th><th>Raised at</th><th>Score</th><th>Band</th></tr>
      {% for a in alerts %}
      <tr><td>{{ a.patient_id }}</td><td>{{ a.raised_at }}</td><td>{{ a.score }}</td><td>{{ a.risk_band }}</td></tr>
      {% endfor %}
      {% if not alerts %}<tr><td colspan="4">No alerts raised in the last 24 hours.</td></tr>{% endif %}
    </table>
  </div>
</body>
</html>
"""


def fetch_report_data(dsn: str, sim_day: str) -> tuple[list[dict], list[dict]]:
    with psycopg2.connect(dsn) as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                """
                SELECT rd.patient_id, p.name, p.ward, p.bed,
                       rd.vitals_score, rd.vitals_band, rd.abnormal_test_count,
                       rd.adjusted_risk_score, rd.risk_band, rd.reason_codes,
                       rd.score_delta, rd.delta_direction
                FROM batch.patient_risk_daily rd
                LEFT JOIN reference.patients p ON p.patient_id = rd.patient_id
                WHERE rd.sim_day = %s
                ORDER BY rd.adjusted_risk_score DESC
                """,
                (sim_day,),
            )
            rows = [dict(r) for r in cur.fetchall()]

            cur.execute("""
                SELECT patient_id, raised_at, score, risk_band
                FROM speed.clinical_alerts
                WHERE raised_at >= now() - interval '24 hours'
                ORDER BY raised_at DESC
                LIMIT 50
                """)
            alerts = [dict(r) for r in cur.fetchall()]

    return rows, alerts


def build_ward_chart(rows: list[dict]) -> str:
    band_counts = {"low": 0, "medium": 0, "high": 0}
    for r in rows:
        band_counts[r["risk_band"]] = band_counts.get(r["risk_band"], 0) + 1

    fig, ax = plt.subplots(figsize=(5, 3.2))
    colors = {"low": "#4caf50", "medium": "#ffb300", "high": "#e53935"}
    bands = ["low", "medium", "high"]
    ax.bar(bands, [band_counts[b] for b in bands], color=[colors[b] for b in bands])
    ax.set_ylabel("Patients")
    ax.set_title("Risk band distribution")
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=110)
    plt.close(fig)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def write_csv(rows: list[dict], path: str) -> None:
    fieldnames = [
        "patient_id",
        "name",
        "ward",
        "bed",
        "vitals_score",
        "vitals_band",
        "abnormal_test_count",
        "adjusted_risk_score",
        "risk_band",
        "score_delta",
        "delta_direction",
        "reason_codes",
    ]
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            writer.writerow({k: r.get(k) for k in fieldnames})


def build_report(sim_day: str, dsn: str, reports_dir: str, logger) -> tuple[str, str]:
    rows, alerts = fetch_report_data(dsn, sim_day)
    chart_b64 = build_ward_chart(rows) if rows else ""

    html = Template(REPORT_TEMPLATE).render(sim_day=sim_day, rows=rows, alerts=alerts, chart_b64=chart_b64)

    os.makedirs(reports_dir, exist_ok=True)
    html_path = os.path.join(reports_dir, f"daily_risk_report_{sim_day}.html")
    csv_path = os.path.join(reports_dir, f"daily_risk_report_{sim_day}.csv")

    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write(html)
    write_csv(rows, csv_path)

    logger.info("report_built", stage="serving", sim_day=sim_day, patients=len(rows), html_path=html_path)
    return html_path, csv_path


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--sim-day", required=True)
    args = parser.parse_args()

    settings = get_settings()
    logger = configure_logging("report-builder", logs_dir=os.environ.get("LOGS_DIR"))
    reports_dir = os.environ.get("REPORTS_DIR", settings.reports_dir)

    build_report(args.sim_day, settings.postgres_dsn_vitals, reports_dir, logger)


if __name__ == "__main__":
    main()
